server:
  port: 8888

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_vue_chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 19930919
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 50
        min-idle: 0
    timeout: 60000
    lettuce:
      shutdown-timeout: 0
# 邮件配置
  mail:
    username: your username
    password: your password
    host: smtp.163.com
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8


# mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
