server:
  port: 8888

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_vue_chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 19930919
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 50
        min-idle: 0
    timeout: 60000
    lettuce:
      shutdown-timeout: 0


# mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Redis配置
spring.redis.database=0
3
# Redis服务器地址
4
spring.redis.host=192.168.0.24
5
# Redis服务器连接端口
6
spring.redis.port=6379
7
# Redis服务器连接密码（默认为空）
8
spring.redis.password=
9
# 连接池最大连接数（使用负值表示没有限制）
10
spring.redis.pool.max-active=200
11
# 连接池最大阻塞等待时间（使用负值表示没有限制）
12
spring.redis.pool.max-wait=-1
13
# 连接池中的最大空闲连接
14
spring.redis.pool.max-idle=10
15
# 连接池中的最小空闲连接
16
spring.redis.pool.min-idle=0
17
# 连接超时时间（毫秒）
18
spring.redis.timeout=1000